version: '3.4'

services:
  merchandising:
    image: ${DOCKER_REGISTRY-}merchandising
    build:
      context: .
      dockerfile: Merchandising/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
      