PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Product;

CREATE TABLE Category (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	TITLE NVARCHAR (200), 
	MIN_STOCK INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Product (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	TITLE NVARCHAR (200) NOT NULL, 
	CATEGORY INTEGER REFERENCES Category (ID) ON DELETE CASCADE ON UPDATE CASCADE, 
	STOCK INTEGER NOT NULL DEFAULT 0, 
	CREATION_TIME DATETIME DEFAULT (datetime('now')), 
	ACTIVE BIT DEFAULT 0
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;